name: dispatch target file updated
on:
  push:
    branches:
      - main
    paths:
      - '.pdf'
jobs:
  dispatch-target-updated:
    strategy:
      matrix:
        repo: ['YuyaMurakamiMath/MyNote']
    name: dispatch-target-updated
    runs-on: ubuntu-latarget
    steps:
      - name: dispatch target-updated
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: target-updated
